GET http://localhost:3001/api/articles HTTP/1.1

###

POST http://localhost:3001/api/articles HTTP/1.1
content-type: application/json

{
  "title": "Nocode сервис Bubble.io",
  "createdDate": "2021-10-14 23:33:12",
  "announce": "Паша Шишкин из «Карьерного цеха» рассказал о своем кейсе на Bubble — без цензуры. Он продакт, в бэкграунде — разработка и даже победа в Чемпионате мира по программированию. Паша собрал приложение на Bubble для проекта, который он делает вместе с Глебом Кудрявцевым из Skyeng.",
  "fullText": "В «Цехе» много разных страниц. Самое интересное: регистрация с анкетой, загрузка выполненного тестового, рейтинг работ других ребят и оценка. Все пришлось делать через эксперименты. Мне очень понравились настройки приватности — они гибкие, удобные и обеспечивают хорошую защиту. Например, нельзя задебажить API, подставить какой-то ID и посмотреть чужие работы. Есть и проблемы — те же поля в формах не могут принимать пустые значения, обязательно надо что-то выбрать, хотя бы дефолтные значения.",
  "category": ["Разное", "Программирование"]
}

###

GET http://localhost:3001/api/articles/QEvbGi HTTP/1.1

###

PUT http://localhost:3001/api/articles/QEvbGi HTTP/1.1
content-type: application/json

{
  "id": "QEvbGi",
  "title": "Что-то о пчёлках",
  "createdDate": "2021-03-30 23:40:21",
  "announce": "Золотое сечение — соотношение двух величин, гармоническая пропорция. Высокий спрос на изделия из дерева объясняется их прочностью, долговечностью и роскошным видом. Из под его пера вышло 8 платиновых альбомов. Достичь успеха помогут ежедневные повторения.",
  "fullText": "Автор синтезировал из самых эффективных методик и наиболее эффективных принципов ясное прагматичное руководство. Собрать камни бесконечности легко, если вы прирожденный герой. Он написал больше 30 хитов. Освоить вёрстку несложно. Возьмите книгу новую книгу и закрепите все упражнения на практике. Этот смартфон — настоящая находка. Большой и яркий экран, мощнейший процессор — всё это в небольшом гаджете. Получайте опыт и изучайте язык на множестве примеров, выполняя упражнения и учебные проекты. Программировать не настолько сложно, как об этом говорят. Первая большая ёлка была установлена только в 1938 году. Альбом стал настоящим открытием года. Мощные гитарные рифы и скоростные соло-партии не дадут заскучать.",
  "сategory": ["Деревья"]
}

###

DELETE http://localhost:3001/api/articles/L_fMHK HTTP/1.1

###

GET http://localhost:3001/api/articles/4tdD4B/comments HTTP/1.1

###

POST  http://localhost:3001/api/articles/4tdD4B/comments HTTP/1.1
content-type: application/json

{
  "text": "Тестовый комментарий"
}

###

DELETE  http://localhost:3001/api/articles/4tdD4B/comments/GYkxp2 HTTP/1.1

###

GET http://localhost:3001/api/categories HTTP/1.1

###

GET http://localhost:3001/api/search?query=о%20паттернах HTTP/1.1
